### ISSUE TITLE
Use @eth-optimism/dev package

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/smock#18]
[@eth-optimism/dev](https://github.com/ethereum-optimism/dev) is a simple npm package that automatically imports many of the common packages we use when developing our various TypeScript modules. It allows us to remove some dependencies and standardizes the way we configure certain things. I'd like to add that package to this module.

Here's a step-by-step of how to do this:
1. Install `@eth-optimism/dev`. We'll put this in our dev dependencies.
```bash
yarn add @eth-optimism/dev --dev
```
2. Remove (newly) unnecessary packages:
```bash
yarn remove @types/chai @types/chai-as-promised @types/mocha @types/node ts-node tslint tslint-config-prettier tslint-no-focused-test tslint-plugin-prettier typescript
```
3. Update `tslint.json` to use extend the [shared `tslint.json` config file](https://github.com/ethereum-optimism/dev/blob/master/tslint.json).
```json
{
  "extends": "@eth-optimism/dev/tslint.json"
}
```

That should be it! Make sure to run `yarn lint` before making a pull request :-)

**Comment by MichaelMacaulay** [comment]
I'd like to claim this issue.

**Comment by gakonst** [comment]
Hey @MichaelMacaulay I think there might be some confusion here regarding [your PR](https://github.com/ethereum-optimism/dev/pull/2): The `eth-optimism/dev` package is good as-is, what @smartcontracts meant is that you should open a PR in _this_ repository, removing these deps!

**Comment by smartcontracts** [comment]
Whoops, sorry for any confusion. @gakonst is correct. @MichaelMacaulay Are you still interested in tackling this?

**Comment by MichaelMacaulay** [comment]
Sorry about that! I'd love to tackle this issue.
