### ISSUE TITLE
Use @eth-optimism/core-utils package

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/smock#22]
**Is your feature request related to a problem? Please describe.**
We're trying to consolidate our usage of common utilities. All of the utilities listed below are now included in `@eth-optimism/core-utils`:

https://github.com/ethereum-optimism/smock/blob/617b8ba87caf1fff91cbec461ee0ab2e1a6d1413/src/utils/hex-utils.ts#L4-L18

We should remove these utilities and instead use the ones from `@eth-optimism/core-utils`. Note that `toHexString32` should *not* be removed as we don't have an equivalent in `core-utils`.

**Describe the solution you'd like**
Remove the above utility functions from this codebase and `yarn add @eth-optimism/core-utils` instead. Make sure to update all imports of the above functions. Easy enough!

**Comment by platocrat** [comment]
Here ye! Here ye! 
I hereby claim this issue as mine to solve.

**Comment by transmissions11** [comment]
lmao
