### ISSUE TITLE
TypeError when used with hardhat-gas-reporter

### ISSUE THREAD

**Issue by ayobuenavista** [ethereum-optimism/smock#24]
**Describe the bug**
smockit fails in test when hardhat-gas-reporter plugin is used.

**To Reproduce**
Import **hardhat-gas-reporter** in `hardhat.config.js`.

In the test:
```js
const MyContractFactory = await ethers.getContractFactory('MyContract')
const MyContract = await MyContractFactory.deploy(...)
const MyMockContract = await smockit(MyContract) // fails here
```

Fails with error:
```
TypeError: provider._init is not a function
      at exports.smockit (node_modules/@eth-optimism/smock/src/smockit/smockit.ts:22:35)
```

Always reproducible. Instantly works when `hardhat-gas-reporter` is removed.

**Comment by smartcontracts** [comment]
Ah okay, I have a feeling I know why this is happening. Next release of smock *should* fix this issue.

**Comment by smartcontracts** [comment]
Issue is specifically in this (old) code: https://github.com/ethereum-optimism/smock/blob/694439baef07b3a57e571173573e8a57131379d4/src/smockit/smockit.ts#L17-L20

**Comment by smartcontracts** [comment]
New release should be out by the end of the week.

**Comment by smartcontracts** [comment]
As noted in the below comment, `1.0.0-alpha.2` has been released. I'm looking for people to start playing with it just in case there are any obvious bugs. I would be extremely grateful if you could give it a shot and see if this error still comes up! (It should be fixed in that release).

https://github.com/ethereum-optimism/smock/issues/3#issuecomment-806158083

**Comment by ayobuenavista** [comment]
> As noted in the below comment, `1.0.0-alpha.2` has been released. I'm looking for people to start playing with it just in case there are any obvious bugs. I would be extremely grateful if you could give it a shot and see if this error still comes up! (It should be fixed in that release).
> 
> [#3 (comment)](https://github.com/ethereum-optimism/smock/issues/3#issuecomment-806158083)

Tried with the latest `1.0.0-alpha.3`. Issue is fixed! So I think the bug is resolved.

**Comment by smartcontracts** [comment]
Fantastic!
